#!/bin/sh
# to skip this, run with the --no-verify argument
# i.e. - $ 'git push --no-verify'

RED="\033[0;31m"
LRED="\033[1;31m"
YEL="\033[0;33m"
LYEL="\033[1;33m"
GRN="\033[0;32m"
LGRN="\033[1;32m"
NCL="\033[0m"

printf "${YEL}running pre-push : ${LYEL}clean build${NCL}\n"

# run the checkstyle and tests with the gradle wrapper
./gradlew clean build

# store the last exit code in a variable
RESULT=$?

if [ "$RESULT" = 0 ] ; then
	printf "${GRN}pre-push - ${LGRN}PASSED${NCL}\n"
else
	printf "${RED}pre-push - ${LRED}FAILED${NCL}\n"
fi

# return the exit code
exit $RESULT
